// commonjs used for required and module used for module sytext in type
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
console.log("Hello Words");
